config/routes.rb
Rails.application.routes.draw do

  resources :products, only: [:index, :show]
  resources :purchase_orders, only: [:index, :new, :show]
  resources :stock_orders, only: [:index, :new, :show]
  resources :all_orders, only: [:index]

  get 'create_purchase_orders' => 'purchase_orders#create'
  get 'create_stock_orders' => 'stock_orders#create'

  root to: 'purchase_orders#index'

end

app/models/concerns/abstract_item.rb
module AbstractItem
  extend ActiveSupport::Concern

  included do
    validates :order, presence: true
    validates :product, presence: true
    validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 127 }
    validates :product_quantity_cache, presence: true, numericality: true

    default_scope -> { order(created_at: :desc) }

    after_initialize do |item|
      item.quantity ||= 0
    end

    before_validation do |item|
      item.product_quantity_cache = last_product_quantity + quantity_diff if new_record?
    end

    def last_product_quantity
      if item = product.last_order_item
        item.product_quantity_cache
      else
        0
      end
    end
  end
end

app/models/concerns/abstract_order.rb
module AbstractOrder
  def items_size
    items.size
  end

  def items_size_all_nonzero?
    items.all? do |item|
      item.quantity.nonzero?
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :stock_order_items, dependent: :destroy
  has_many :purchase_order_items, dependent: :destroy

  # mount_uploader :image, ImageUploader

  validates :price, numericality: { grater_than: 0 }

  def quantity
    if item = last_order_item
      item.product_quantity_cache
    else
      0
    end
  end

  def last_order_item
    stock    = stock_order_items.first
    purchase = purchase_order_items.first

    if stock and purchase
      stock.created_at > purchase.created_at ? stock : purchase
    else
      stock or purchase
    end
  end

  def order_items
    @order_items ||= (stock_order_items + purchase_order_items).sort_by(&:created_at)
  end
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  include AbstractOrder

  has_many :items, class_name: PurchaseOrderItem, dependent: :destroy

  # validates :orderer_name, presence: true, length: { maximum: 100 }
  validates :items_size, numericality: { greater_than: 0 }
  validates :items_size_all_nonzero?, inclusion: { in: [true] }
end

app/models/purchase_order_item.rb
class PurchaseOrderItem < ActiveRecord::Base
  include AbstractItem

  belongs_to :order, class_name: PurchaseOrder, foreign_key: :purchase_order_id
  belongs_to :product

  def quantity_diff
    0 - quantity
  end
end

app/models/stock_order.rb
class StockOrder < ActiveRecord::Base
  include AbstractOrder

  has_many :items, class_name: StockOrderItem, dependent: :destroy

  # validates :orderer_name, presence: true, length: { maximum: 100 }
  validates :items_size, numericality: { greater_than: 0 }
  validates :items_size_all_nonzero?, inclusion: { in: [true] }
end

app/models/stock_order_item.rb
class StockOrderItem < ActiveRecord::Base
  include AbstractItem

  belongs_to :order, class_name: StockOrder, foreign_key: :stock_order_id
  belongs_to :product

  def quantity_diff
    0 + quantity
  end
end

app/controllers/all_orders_controller.rb
class AllOrdersController < OrdersController
  def index
    @orders = PurchaseOrder.limit(10) + StockOrder.limit(10)
    @orders.sort_by(&:created_at)
    @products = Product.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def set_cors_header
    headers['Access-Control-Allow-Origin'] = "*"
  end
end

app/controllers/concerns/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_new_order, only: [:new, :create]
  before_action :set_order, only: [:show]

  def index
    @orders = order_model.limit(20)
    @products = Product.all

    respond_to do |format|
      set_cors_header
      format.json { render 'orders/index.json' }
      format.html
    end
  end

  def new
  end

  def create
    set_params_order

    respond_to do |format|
      set_cors_header

      if @order.save!
        format.json { render json: @products }
      else
        format.json { render json: @order.errors.full_messages, status: :bad_request }
      end
    end
  end

  def show
    set_cors_header
  end

  private

  def params_order
    params.require(:order).permit(:orderer_name, items: [:product_id, :quantity])
  end

  def set_new_order
    @order = order_model.new
  end

  def set_params_order
    @order.assign_attributes(orderer_name: params_order[:orderer_name])

    params_order[:items].each do |key, item|
      product  = Product.find(item[:product_id])
      quantity = item[:quantity]

      @order.items.build(product: product, quantity: quantity, order: @order) if quantity and quantity.to_i.nonzero?
    end
  end

  def set_order
    @order = order_model.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @orders   = PurchaseOrder.limit(10) + StockOrder.limit(10)
    @orders.sort_by(&:created_at)

    respond_to do |format|
      set_cors_header
      format.json { render json: @products }
      format.html
    end
  end

  def show
    @product = Product.find(params[:id])
    set_cors_header
  end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < OrdersController

  private

  def order_model
    PurchaseOrder
  end
end

app/controllers/stock_orders_controller.rb
class StockOrdersController < OrdersController
  private

  def order_model
    StockOrder
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/helpers/stock_orders_helper.rb
module StockOrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StockManager</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

<div class="footer">
  <div class="container">
    <%= link_to "卸売り店様向け", purchase_orders_path %>
    <%= link_to "メーカー向け", products_path %>
    <%= link_to "工場向け", stock_orders_path %>
  </div>
</div>

</body>
</html>

app/views/products/index.html.erb
<ol class="breadcrumb products">
  <li><%= link_to "製品一覧", products_path %></li>
</ol>

<table>
  <thead>
    <th></th>
    <% @products.each do |product| %>
      <th>
        <p>
          <%= product.name %>
        </p>

        <img src="<%= product.image %>" width="60" height="60">
      </th>
    <% end %>
    <th></th>
  </thead>
  <tbody>
    <th></th>
    <% @products.each do |product| %>
      <th><%= product.quantity %></th>
    <% end %>
    <th></th>
  </tbody>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <% case order %>
          <% when PurchaseOrder %>
            出荷
          <% when StockOrder %>
            入荷
          <% end %>
        </td>
        <% @products.each do |product| %>
          <td>
            <% case item = order.items.find{ |item| item.product == product } %>
            <% when PurchaseOrderItem %>
              - <%= item.quantity %>
            <% when StockOrderItem %>
              + <%= item.quantity %>
            <% end %>
          </td>
        <% end %>
        <td>
          <%= order.created_at.strftime "%Y/%m/%d %H:%M" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/show.html.erb
<ol class="breadcrumb products">
  <li><%= link_to "製品一覧", products_path %></li>
  <li><%= @product.name %></li>
</ol>

<h1><%= @product.name %></h1>

<% @product.order_items.each do |item| %>
  <div>
    <div>
      <%= item.created_at.strftime "%Y/%m/%d %H:%M" %>
    </div>
    <div>
      <%= item.quantity %>個
    </div>
    <div>
      <% case item %>
      <% when PurchaseOrderItem %>
        出荷
      <% when StockOrderItem %>
        入荷
      <% end %>
    </div>
  </div>
  <hr>
<% end %>

app/views/purchase_orders/index.html.erb
<ol class="breadcrumb purchase_orders">
  <li><%= link_to "発注書一覧", purchase_orders_path %></li>
</ol>

<%= link_to "発注書を作成する", new_purchase_order_path %>

<hr>

<table>
  <thead>
    <% @products.each do |product| %>
      <th>
        <p>
          <%= product.name %>
        </p>

        <img src="<%= product.image %>" width="60" height="60">
      </th>
    <% end %>
    <th></th>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <% @products.each do |product| %>
          <td>
            <% case item = order.items.find{ |item| item.product == product } %>
            <% when PurchaseOrderItem %>
              <%= item.quantity %>
            <% when StockOrderItem %>
              <%= item.quantity %>
            <% else %>
              0
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/purchase_orders/new.html.erb
<ol class="breadcrumb purchase_orders">
  <li><%= link_to "home", root_path %></li>
  <li><%= link_to "new", new_purchase_order_path %></li>
</ol>

<form id="new_order">
  <div id="products">
  </div>

  <div class="col-xs-12">
    <input type="submit" value="送信" class="btn btn-default" />
  </div>
</form>

<script type="text/javascript">
  $(function(){

    var products  = [];
    var $form     = $('#new_order');
    var $products = $('#products');

    var template = function(product){
      var temp = "";
      var name = "product_" + product.id;

      temp += "<div id='product' class='col-md-4 text-center'>";
      temp +=   "<img src='/" + product.image +  "'' width='120' height='120'>";
      temp +=   "<p>" + product.name + "</p>"
      temp +=   "<label for='" + name + "_quantity'>数量</label> : "
      temp +=   "<input id='" + name + "_quantity' type='number' name='" + name + "' value=0>"
      temp += "</div>";

      return temp;
    };

    $.ajax('/products', {
      type: "GET",
      success: function(data, status, xhr){

        data.forEach(function(attrs){
          var product = new Product(attrs);
          products.push(product);
        });

        products.forEach(function(product){
          $products.append(template(product));

          var $product = $products.find("input[name=product_" + product.id + "]");
          var onChange = function(e){
            product.quantity = $product.val();
          }

          $product.on('change keyup', onChange);
        });

        $form.submit(function(e){
          e.stopPropagation();
          e.preventDefault();

          if(window.confirm("発注します。よろしいですか？")){

            var json = {};
            json.items = [];

            json.orderer_name = "ohataken";

            products.forEach(function(product){
              var hash = { product_id: product.id, quantity: product.quantity };
              json.items.push(hash);
            });

            $.ajax('/purchase_orders', {
              type: 'POST',
              contentType: 'application/json',
              data: JSON.stringify({order: json}),
              success: function(data, status, xhr){
                location.assign("/");
              }
            })

          }
        });
      },
    });
  });
</script>

app/views/purchase_orders/show.html.erb
<ol class="breadcrumb purchase_orders">
  <li><%= link_to "発注書一覧", purchase_orders_path %></li>
  <li><%= @order.created_at.strftime "%Y/%m/%d %H:%m" %>の発注書</li>
</ol>

<h1>発注書</h1>

発注日時: <%= @order.created_at.strftime " %Y/%m/%d %H:%m" %>

<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>数量</th>
      <th>単価</th>
    </tr>
  </thead>
  <tbody>
    <%- @order.items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.product.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stock_orders/index.html.erb
<ol class="breadcrumb stock_orders">
  <li><%= link_to "納品書一覧", stock_orders_path %></li>
</ol>

<%= link_to "納品書を作成する", new_stock_order_path %>

<hr>

<table>
  <thead>
    <% @products.each do |product| %>
      <th>
        <p>
          <%= product.name %>
        </p>

        <img src="<%= product.image %>" width="60" height="60">
      </th>
    <% end %>
    <th></th>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <% @products.each do |product| %>
          <td>
            <% case item = order.items.find{ |item| item.product == product } %>
            <% when PurchaseOrderItem %>
              <%= item.quantity %>
            <% when StockOrderItem %>
              <%= item.quantity %>
            <% else %>
              0
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stock_orders/new.html.erb
<ol class="breadcrumb stock_orders">
  <li><%= link_to "home", root_path %></li>
  <li><%= link_to "new", new_purchase_order_path %></li>
</ol>

<form id="new_order">
  <div id="products">
  </div>

  <div class="col-xs-12">
    <input type="submit" value="送信" class="btn btn-default" />
  </div>
</form>

<script type="text/javascript">
  $(function(){

    var products  = [];
    var $form     = $('#new_order');
    var $products = $('#products');

    var template = function(product){
      var temp = "";
      var name = "product_" + product.id;

      temp += "<div id='product' class='col-md-4 text-center'>";
      temp +=   "<img src='/" + product.image +  "'' width='120' height='120'>";
      temp +=   "<p>" + product.name + "</p>"
      temp +=   "<label for='" + name + "_quantity'>数量</label> : "
      temp +=   "<input id='" + name + "_quantity' type='number' name='" + name + "' value=0>"
      temp += "</div>";

      return temp;
    };

    $.ajax('/products', {
      type: "GET",
      success: function(data, status, xhr){

        data.forEach(function(attrs){
          var product = new Product(attrs);
          products.push(product);
        });

        products.forEach(function(product){
          $products.append(template(product));

          var $product = $products.find("input[name=product_" + product.id + "]");
          var onChange = function(e){
            product.quantity = $product.val();
          }

          $product.on('change keyup', onChange);
        });

        $form.submit(function(e){
          e.stopPropagation();
          e.preventDefault();

          if(window.confirm("納品します。よろしいですか？")){
            var json = {};
            json.items = [];

            json.orderer_name = "ohataken";

            products.forEach(function(product){
              var hash = { product_id: product.id, quantity: product.quantity };
              json.items.push(hash);
            });

            $.ajax('/stock_orders', {
              type: 'POST',
              contentType: 'application/json',
              data: JSON.stringify({order: json}),
              success: function(data, status, xhr){
                location.assign("/stock_orders");
              }
            })
          };
        });
      },
    });
  });
</script>

app/views/stock_orders/show.html.erb
<ol class="breadcrumb stock_orders">
  <li><%= link_to "納品書一覧", stock_orders_path %></li>
  <li><%= @order.created_at.strftime " %Y/%m/%d %H:%m" %>の納品書</li>
</ol>

<h1>納品書</h1>

納品日時: <%= @order.created_at.strftime " %Y/%m/%d %H:%m" %>

<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>数量</th>
      <th>単価</th>
    </tr>
  </thead>
  <tbody>
    <%- @order.items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.product.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>